services:
  app:
    build:
      context: r-omni
      dockerfile: Dockerfile
    container_name: nestjs_app
    restart: always
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
#      - DATABASE_URL=postgresql://postgres:postgres@db:5432/nestdb