services:
  app:
    build:
      context: r-omni
      dockerfile: apps/r-omni/Dockerfile
    container_name: nestjs_app
    restart: always
    ports:
      - '3002:3002'
    environment:
      - PORT=3002
      - NODE_ENV=development
      - NATS_URL=nats://nats-server:4222
    depends_on:
      - nats-server
    networks:
      - nats-network

  user:
    build:
      context: r-omni
      dockerfile: apps/user/Dockerfile
    container_name: user
    restart: always
    environment:
      - NODE_ENV=development
      - NATS_URL=nats://nats-server:4222
    depends_on:
      - nats-server
    networks:
      - nats-network

  nats-server:
    image: nats:2.11.6
    container_name: nats-server
    command: --http_port 8222 -DV
    ports:
      - "4222:4222"
      - "8222:8222"
    restart: unless-stopped
    networks:
      - nats-network

networks:
  nats-network:
    driver: bridge