services:
  app:
    build:
      context: r-omni
      dockerfile: Dockerfile
    container_name: nestjs_app
    restart: always
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
#      - DATABASE_URL=postgresql://postgres:postgres@db:5432/nestdb

  nats-server:
    image: nats:latest
    container_name: nats-server
    command: --http_port 8222 -DV
    ports:
      - "4222:4222"  # Клиентские подключения (NATS)
      - "8222:8222"  # Мониторинг (HTTP)
    restart: unless-stopped
    networks:
      - nats-network

networks:
  nats-network:
    driver: bridge