services:
  app:
    build:
      context: r-omni
      dockerfile: Dockerfile
    container_name: nestjs_app
    restart: always
#    ports:
#      - '3000:3000'
    environment:
      - NODE_ENV=development
#      - DATABASE_URL=postgresql://postgres:postgres@db:5432/nestdb