services:
  app:
    build:
      context: r-omni
      dockerfile: apps/r-omni/Dockerfile
    container_name: nestjs_app
    restart: unless-stopped
    ports:
      - '3002:3002'
    environment:
      - PORT=3002
      - NODE_ENV=development
      - NATS_URL=nats://nats-server:4222
    depends_on:
      - nats-server
    networks:
      - nats-network

  user:
    build:
      context: r-omni
      dockerfile: apps/user/Dockerfile
    container_name: user
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - NATS_URL=nats://nats-server:4222
      - DB_NAME=auth_service_db
      - DB_HOST=auth_service_db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      nats-server:
        condition: service_started
      auth_service_db:
        condition: service_healthy
    command: sh -c "yarn migration:users:up && yarn start:dev user"
    networks:
      - nats-network

  auth_service_db:
    image: postgres:17.5
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_service_db
    ports:
      - '54320:5432'
    volumes:
      - auth_service_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - nats-network

  booking:
    build:
      context: r-omni
      dockerfile: apps/booking/Dockerfile
    container_name: booking
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - NATS_URL=nats://nats-server:4222
      - DB_NAME=booking_service_db
      - DB_HOST=booking_service_db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      nats-server:
        condition: service_started
      auth_service_db:
        condition: service_healthy
    command: sh -c "yarn migration:booking:up && yarn start:dev booking"
    networks:
      - nats-network

  booking_service_db:
    image: postgres:17.5
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=booking_service_db
    ports:
      - '54321:5432'
    volumes:
      - booking_service_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - nats-network

  room:
    build:
      context: r-omni
      dockerfile: apps/rooms/Dockerfile
    container_name: room
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - NATS_URL=nats://nats-server:4222
      - DB_NAME=room
      - DB_HOST=room_service_db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      nats-server:
        condition: service_started
      auth_service_db:
        condition: service_healthy
    command: sh -c "yarn migration:room:up && yarn start:dev room"
    networks:
      - nats-network

  room_service_db:
    image: postgres:17.5
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=room_service_db
    ports:
      - '54322:5432'
    volumes:
      - room_service_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - nats-network

  nats-server:
    image: nats:2.11.6
    container_name: nats-server
    command: --http_port 8222 -DV
    ports:
      - "4222:4222"
      - "8222:8222"
    restart: unless-stopped
    networks:
      - nats-network

networks:
  nats-network:
    driver: bridge

volumes:
  auth_service_data:
  booking_service_data:
  room_service_data: